@startuml
(*) -->"Start"
if "Is it planned?" then
partition "Preproduction" {
    --left> [true] "Story / scripts"
    --left> "Actors"
    --left> "Intro"
    --left> "Scenes"
    -left-> "Location"
}
--> "Shoot"
else
-->[false] "Shoot"
endif
partition PostProduction {
    --> "Backup all videos" as B
    --> "[[https://en.wikipedia.org/wiki/Rough_cut Rough cut]]" as RC
    --> "Sync sound\nif recorded separately"
    --> "Find and add music"
    --> "End screen\n20 seconds"
    --> "Render" as R
    R --> "Upload" as U
    
    B -right-> "Thumbnail"
    note right: Better create separately \nthan automatic from youtube
    --> U
    --> "Sub title"
    note right:Do not render into video, use SRT
    --> "End Screen"
}
partition "Post publish"{
    --> "Share in social media"
}
-->(*)
@enduml
