@startuml
Title YouTube publishing workflow
center header
Beginner workflow for YouTube videos
endheader
(*) -->"Start"
if "Is it planned?" then
partition "Preproduction" {
    --left> [true] "Story / scripts"
    --left> "Actors"
    --left> "Intro"
    --left> "Scenes"
    -left-> "Location"
}
--> "Shoot"
else
-->[false] "Shoot"
endif
partition PostProduction {
    --> "Backup all videos" as B
    --> "[[https://en.wikipedia.org/wiki/Rough_cut Rough cut]]" as RC
    --> "Sync sound\nif recorded separately"
    --right> "Find and add music"
    --> "Visual for end screen\n20 seconds"
    note right:This is specific for YouTube
    --> "Render" as R
    B -right-> "Thumbnail"
    note right: Better create separately \nthan automatic from youtube
}
partition YouTubeUpload {

    R --> "Upload" as U
    U --> "Sub title" as ST
    note left:Do not render into video\n use SRT
    ST--right> "Set Thumbnail" as STN
    STN --right> "Video chapters" as VC
    VC --right> "Add end screen" as ES
    ES --right> "Mask faces \nif applicable " as MF
}
partition "Post publish"{
    --> "Share in social media" as SM

}
-->(*)
center footer JoymonOnline

legend right
  - 2 lines starting from a node means it can be done in parallel.
endlegend

@enduml