@startmindmap
caption Video editing - Updated on 2020-05-12
title Video editing - Mind map
center header
Video editing
endheader

* <&flag><b>Video Publishing</b>

** Post Production
*** Dare to remove scenes
*** Special effects
**** Music
***** Free
****** [[https://www.youtube.com/audiolibrary/music?nv=1 YouTube]]
**** Sounds
***** Free
****** [[https://www.youtube.com/audiolibrary/soundeffects?nv=1 YouTube]]
****** [[https://soundbible.com/ soundbible.com]]
****** [[https://freesfx.co.uk/ freesfx.co.uk]]
****** [[https://freesound.org/ freesound.org]]
**** Video clips
***** Free
****** [[https://www.videezy.com/ Videezy.com]]
****** [[https://www.videvo.net/ videvo.net]]
******* Youtube channels
******** [[https://www.youtube.com/channel/UC8ScFr0TdBPz9bLElei6-VA/videos Video Libary]]
**** Slow motion .25x FPS, Fast 2x FPS
*** Duration 15-20 mins Home,10 Mins Pro
*** 20 secs end screen
*** Thumbnail
**** Spark.Adobe - Bright, readable
*** Format-MP4+AAC-LC+H.264+30FPS+1080P+8Mbps
*** Sub titles
** Post Publishing
*** Twitter
*** FB
*** WhatsApp
*** LinkedIn

left side
** Production
*** Lighting
*** Mic volumne
*** Format
**** 60FPS
**** 1080P
** Pre production
*** Intro 15 secs
*** Story
**** Start
**** Middle
**** Ending
****  Call for action/comment
*** Scenes
**** A Roll & B Roll

center footer JoymonOnline

legend right
  Left Side - preparations
  Right Side - production and post production
  Free footages - [[https://www.oberlo.com/blog/free-stock-video-websites list1]]
endlegend
@endmindmap