@startmindmap
caption Video editing - Updated on 2020-05-12
title Video Publishing - Mind map
center header
Video editing
endheader

* <&flag><b>Video Publishing</b>

** Post Production
*** Tools
**** Life Videos
***** Editor - [[https://shotcut.org/download/ Shotcut]]
**** Cut and merge - [[https://github.com/mifi/lossless-cut/releases LosslessCut]]

*** Dare to remove scenes
*** Special effects
**** Audio
***** Music
****** Free
******* [[https://www.youtube.com/audiolibrary/music?nv=1 YouTube]]
***** Sounds
****** Free
******* [[https://www.youtube.com/audiolibrary/soundeffects?nv=1 YouTube]]
******* [[https://soundbible.com/ soundbible.com]]
******* [[https://freesfx.co.uk/ freesfx.co.uk]]
******* [[https://freesound.org/ freesound.org]]
**** Video clips
***** Free
****** [[https://www.videezy.com/ Videezy.com]]
****** [[https://www.videvo.net/ videvo.net]]
****** Youtube channels
******* [[https://www.youtube.com/channel/UC8ScFr0TdBPz9bLElei6-VA/videos Video Libary]]
**** Slow motion .25x FPS, Fast 2x FPS
**** Transitions
*** 20 secs end screen
*** Rendering
**** Format-MP4+AAC-LC+H.264+30FPS+1080P+8Mbps
**** Sub titles (SRT)
*** Thumbnail
**** Spark.Adobe - Bright, readable
*** YouTube
**** Mask faces
**** Video chapters
***** Thumbnail
****** Tags
******* End screen
**** Video location 
***** Video Language
****** Recording date
******* Video category

** Post Publishing
*** Twitter
*** FB
*** WhatsApp
*** LinkedIn

left side
** Production
*** Life videos
**** Lighting
**** Mic volumne
**** Format
***** 60FPS
***** 1080P
**** Duration
***** 10-15 mins Home
*** Screen cast
**** 10 Mins
**** Software
***** Screen record [[https://atomisystems.com/download/ ActivePresenter]]
***** Streaming - [[https://obsproject.com/download OBS Studio]]
***** [[https://www.e2esoft.com/ivcam/ iVCam Mobile as cam]]
***** [[https://www.apowersoft.com/phone-mirror Mirror mobile]]
** Pre production
*** Intro 15 secs
*** Story
**** Start
**** Middle
**** Ending
****  Call for action/comment
*** Scenes
**** A Roll & B Roll
** Channel setup
*** Channel art
**** [[https://snappa.com/ Snappa]]
*** FB Page
center footer JoymonOnline

legend right
  Left Side - preparations
  Right Side - production and post production
  Free footages - [[https://www.oberlo.com/blog/free-stock-video-websites list1]]
endlegend
@endmindmap