@startmindmap
caption Video editing - Updated on 2019-11-21
title Video editing - Mind map
center header
Video editing
endheader

* <&flag><b>Video Publishing</b>
** Production
*** Lighting
*** Mic volumne
*** Format
**** 60FPS
**** 1080P
** Post Production
*** Dare to remove scenes
*** Music to suit
*** Slow motion .25x FPS, Fast 2x FPS
*** Duration 15-20 mins Home,10 Mins Pro
*** Thumbnail
**** Spark.Adobe - Bright, readable
*** Format-MP4+AAC-LC+H.264+30FPS+1080P+8Mbps

left side
** Pre production
*** Intro 15 secs
*** Story
**** Start
**** Middle
**** Ending
****  Call for action/comment
*** Scenes
**** A Roll & B Roll
** Post Publishing
*** Twitter
*** FB
*** WhatsApp
*** LinkedIn

center footer JoymonOnline

legend right
  Left Side - preparations
  Right Side - production and post production
endlegend
@endmindmap